package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"original-card-game-backend/internal/presentation/graphql/core"
)

// Mutation returns core.MutationResolver implementation.
func (r *Resolver) Mutation() core.MutationResolver { return &mutationResolver{r} }

// Query returns core.QueryResolver implementation.
func (r *Resolver) Query() core.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
