// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Text      string `json:"text"`
	CreatedBy *User  `json:"createdBy"`
	UpdatedBy *User  `json:"updatedBy"`
}

type CreateCardInput struct {
	Name string `json:"name"`
	Text string `json:"text"`
}

type Mutation struct {
}

type Query struct {
}

type Self struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
